# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: circleci/node:8.9.1
      
    steps:
      - checkout

      - run: 
          name: Updating npm 
          command: 'sudo npm install -g npm@latest'

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Installing packages
          command: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
        
  test: 
    docker:
      - image: circleci/node:8.9.1  
    
    steps:
      - checkout
      - run: 
          name: Running tests
          command: npm test

  deploy_staing: 
    steps:
      - run:  
          name: digital-ocean deployment
          command: ssh -o "StrictHostKeyChecking no" deploy@138.68.164.152 "cd ~/API; git pull origin staging; npm install; npm run start"

workflows:
  version: 2
    staging:
      jobs:
        - build
            filters:
              branches:
                only: staging
        - test
            requires: build
            filters:
              branches:
                only: staging
        - deploy
            requires: test
            filters:
              branches:
                only: staging
